---

- name: "Create directories"
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/nginx/sites-available

- name: "Copy configuration"
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
