---

- name: "Create ssl directory"
  file:
    state: directory
    path: "/etc/nginx/ssl"
    mode: 0755
    owner: root
    group: root

- name: "copy CA"
  copy:
    src: root_ca
    dest: /root

- name: "Generate an OpenSSL certificate signed with your own CA certificate"
  openssl_certificate:
    path: /etc/nginx/ssl/{{ domain_name }}.crt
    csr_path: /etc/nginx/ssl/{{ domain_name }}.csr
    ownca_path: /root/root_ca/ca.crt
    ownca_privatekey_path: /root/root_ca/ca.key
    provider: ownca
