---

- hosts: localhost
  connection: local
  roles:
    - infra
  post_tasks:
    - block:
        - name: "create entry in /etc/hosts"
          become: true
          become_method: sudo
          lineinfile:
            path: /etc/hosts
            regexp: '^.*(cuchillos.local)$'
            line: "{{ hostvars['localhost']['my_instance_ip'] }}    cuchillos.local"
            state: present

        - name: "generate static inventory"
          template:
            src: openstack.j2
            dest: "inventory/openstack"
      when: not destroy
