---

gitea_port: 3000
gitea_service: gitea
gitea_version: 1.10.0
gitea_package: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
gitea_user: gitea
gitea_group: gitea
gitea_database: "{{ gitea_service }}_db"
gitea_db_user: gitea
gitea_domain: gitea.cuchillos.local
