- name: "{{ 'create' if not destroy else 'destroy' }} instance in asgard"
  os_server:
    state: "{{ destroy | ternary('absent','present') }}"
    name: "{{ os_instance_name }}"
    image: "{{ os_image }}"
    key_name: "{{ os_keypair }}"
    timeout: 200
    flavor: "{{ os_flavor }}"
    security_groups: default
    delete_fip: true
    nics:
      - net-id: "{{ os_network }}"
    meta:
      hostname: "{{ os_instance_name }}"
      group: mis_huevos

- import_tasks: get_ip.yml
  when: not destroy
  tags:
    - check
