---

- name: "{{ 'create' if not destroy else 'destroy' }} keypair"
  os_keypair:
    name: "{{ os_keypair }}"
    state: "{{ destroy | ternary('absent','present') }}"
    public_key_file: "{{ ansible_user_dir }}/.ssh/id_rsa.pub"
  register: keypair
