---

- name: "install python packages"
  yum:
    name: python2-pip
    state: present
    update_cache: true

- name: "install python modules"
  pip:
    name:
      - pyOpenSSL==19.1.0
      - bs4
      - packaging
