---

- name: "copy repository file"
  copy:
    src: default.repo
    dest: /etc/yum.repos.d/default.repo

- name: "copy epel package"
  copy:
    src: epel-release-7-12.noarch.rpm
    dest: /tmp/epel-release-7-12.noarch.rpm

- name: "install epel"
  yum:
    name: /tmp/epel-release-7-12.noarch.rpm
    state: present

- name: "delete temporal package"
  file:
    path: /tmp/epel-release-7-12.noarch.rpm
    state: absent

- name: "Update all packages"
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: "install redhat packages"
  yum:
    name: "{{ rhel_packages }}"
    state: present
    update_cache: true
  tags:
    - install_packages
