---

- name: "copy repository file"
  copy:
    src: default.repo
    dest: /etc/yum.repos.d/default.repo

- name: "Update all packages"
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: "install redhat packages"
  yum:
    name: "{{ rhel_packages }}"
    state: present
    update_cache: true
  tags:
    - install_packages
